// Code generated by github.com/artyom/usagegen; DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

func init() {
	const usage = "Command pagetest fetches provided url and all linked resources, printing\ndiagnostic timings.\n\npagetest first fetches html page at given url, then parses html, extracting\nabsolute urls from <link>, <script>, <img> tag attributes, then issues HEAD\nrequests to these urls and reports timings and response codes for all requests\ndone.\n\nOn certain requests for the same domain some of the reported timings may be\nzero, this is a result of connection reuse.\n"
	flag.Usage = func() {
		fmt.Fprintln(flag.CommandLine.Output(), usage)
		fmt.Fprintf(flag.CommandLine.Output(), "Usage of %s:\n", filepath.Base(os.Args[0]))
		flag.PrintDefaults()
	}
}
